### PR TITLE
Add author and time info to events

### PR DESCRIPTION
**Pull request by Chilipp**
In this PR, we add information about authors and time of the event to the corresponding pages, as well as to the summary on the `/programme/` page, see https://20-276193679-gh.circle-artifacts.com/0/SORSE/programme/software_demos/event-001/index.html.

We also use cards to display the events on the `/programme/` page, see https://20-276193679-gh.circle-artifacts.com/0/SORSE/programme/index.html

Any comments @vsoch?

### CODE REVIEW

**Comment by Chilipp** [comment]
Actually, we need to change the `date` metadata of the events into something else. A single start and end-date would not work, as a workshop, for instance, might go on one day from time1 to time2, and on another day from time3 to time 4. This also impacts the stuff implemented on #1, @vsoch. What about something like this instead of `date`?

```yaml
time:
    - start: 2020-07-11T18:00:00Z
      end: 2020-07-11T18:30:00Z
    - start: 2020-07-21T18:00:00Z
      end: 2020-07-21T18:30:00Z
```

**Comment by vsoch** [comment]
I think the `post-cards` class would do well with a little padding added - here I'm showing added 20px (top) against the current (bottom):

image

For workshop times, I think your approach is good - to have date/time be a list, that would be akin to having a separate event for each day, then having the same content for the event. With this approach we just create three different calendar links that go to the same page. The other (simplier but less detailed option) is to have the multiple day events show up as all day on the calendar, but then put the specific times in the description. I think the first works better, and then all events would be updated to be a list of times (and possibly only one).

**Comment by Chilipp** [comment]
Yes, I think we better go for the first one. An all-day event might be misleading, particularly if we want to implement the _Add to calendar_ button.

I'll set it up in this PR.

Do you think we should add these information to the generated PDF? My general feeling would be, no

**Comment by vsoch** [comment]
I agree - the PDFs should be timeless, maybe at best have a month / year of "publication."

**Comment by Chilipp** [comment]
@vsoch, I think I am done here. Event times are now included with the structure proposed in https://github.com/Chilipp/sorse.github.io/pull/3#issuecomment-653927294. 

I updated the generation of events for the calendar in 
b357c9e (see https://27-276193679-gh.circle-artifacts.com/0/SORSE/index.html/#upcoming-events) for instance and the rendering of times in [cards](https://27-276193679-gh.circle-artifacts.com/0/SORSE/programme/index.html) and [events](https://27-276193679-gh.circle-artifacts.com/0/SORSE/programme/workshops/event-004/index.html).

I also truncated the dates of the dummy events as mentioned in https://github.com/SORSE/sorse.github.io/pull/218#issuecomment-654469018

**Comment by Chilipp** [comment]
this PR is ready to be merged. Then I can go all the way up to https://github.com/SORSE/sorse.github.io/pull/218

**Review by vsoch — APPROVED** [review]

**Pull request merged**
