### PR TITLE
adding event generation workflow

### PR DESCRIPTION
**Pull request by vsoch**
This will probably need a lot of updates, but here is a first shot, gotta open it sometime!

### CODE REVIEW

**Comment by vsoch** [comment]
@Chilipp I don't see the GitHub workflow running, is there any way I can PR against a branch in the repo here? Might that be the issue?

**Comment by Chilipp** [comment]
hmm, no idea. I just made you a collaborator of this repo so you can make a branch if you think that works

**Comment by Chilipp** [comment]
I could imagine that workflows are not enabled for forks

**Comment by Chilipp** [comment]
from https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions

> Workflows in forked repositories don't run by default.

But I can't find, how to change this. So maybe it's the easiest to move this fork into a branch of SORSE/sorse.github.io

**Comment by vsoch** [comment]
@Chilipp can you push your master to a differently named branch in sorse, tell me the branch name, and I'll open a PR against it? The branch I'm doing the PR from is already at the upstream repo.

**Comment by Chilipp** [comment]
alright, it's in the [add/events](https://github.com/SORSE/sorse.github.io/tree/add/events) branch

**Pull request closed without merging**
